### ISSUE TITLE
RunMTK doesn't work on Windows 11 + Java 64x

### ISSUE THREAD

**Issue by kodavr** [EnterpriseDB/docs#3497]
2023-01-01 17:40:31,099 main ERROR Unable to create file C:\Users\kodav\.enterprisedb\migration-toolkit\logs\mtk_= 2>&1  _20230101054030.log java.io.IOException: The filename, directory name, or volume label syntax is incorrect
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(Unknown Source)
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:733)
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:716)
        at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:114)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:100)
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:217)
        at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:146)
        at com.edb.MigrationToolkit.configureLogging(MigrationToolkit.java:983)
        at com.edb.MigrationToolkit.main(MigrationToolkit.java:1211)

MTK-03000: General Error
java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@13e39c73] unable to create manager for [C:\Users\kodav\.enterprisedb\migration-toolkit\logs\mtk_= 2>&1  _20230101054030.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@64cd705f[pattern=C:\Users\kodav\.enterprisedb\migration-toolkit\logs\mtk_= 2>&1  _20230101054030.log.%i, append=false, bufferedIO=true, bufferSize=8192, policy=SizeBasedTriggeringPolicy(size=104857600), strategy=DefaultRolloverStrategy(min=1, max=10, useMax=false), advertiseURI=null, layout=%d{yyyy-MM-dd HH:mm:ss} %m%n, filePermissions=null, fileOwner=null]]

Trying to change -logDir:
c:\Program Files\edb\mtk\bin>runMTK.bat -logDir A:/Logs
MTK-10027:You have specified invalid command-line arguments. Run runMTK -help to see the usage details.

Running as admin doesn't help. :(

**Comment by drothery-edb** [comment]
@kodavr, for questions such as this, you're best off contacting our support team - you can find our support center at: https://www.enterprisedb.com/services/support
