### ISSUE TITLE
Question about deploy.mjs

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#3601]
## Summary

With https://github.com/EnterpriseDB/docs/pull/3587 we will have completed Phase II of the install template project. If we remove the last chuck of this code in the deploy.mjs file:
```
const destFilename = integralDeploymentPath || match(context,
 	when blah blah
		(ctx) => woof woof
	...
```
we get this error:
```
(node:1) UnhandledPromiseRejectionWarning: ReferenceError: destFilename is not defined
    at moveDoc (file:///app/deploy.mjs:167:3)
    at async run (file:///app/deploy.mjs:31:22)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
If we leave the epas lines in the file, we don't get an error and can deploy the generated files.

Is there some final cleanup to be done in the deploy.mjs file as we complete this phase?

**Comment by josh-heyer** [comment]
Don't remove the section entirely - leave just the assignment of integralDeploymentPath:

```javascript
  const destFilename = integralDeploymentPath;
```

This will work without error. Alternately, leave a do-nothing example there in case we ever want to use this functionality again:

```javascript
  const destFilename = integralDeploymentPath || match(context,   
    when({product: {name: "xdb", version: 99}, platform: {name: "MS-DOS 4.0"}}, 
      (ctx) => `xdb/99/installing/${fmtArchPath(ctx)}/xdb_centos7_${fmtArchFilename(ctx)}.mdx`),
    );
```
