### ISSUE TITLE
Feedback on livecompare 3 - "Command-line usage"

### ISSUE THREAD

**Issue by jenishvyas22** [EnterpriseDB/docs#6355]
### Summary

/usr/bin/livecompare /etc/livecompare/**livecompare_all.ini 17 --recheck** 

Unhandled exception on session 17 at 2024-12-18 18:32:01.629091: 'LiveTable' object has no attribute 'table_exists'
Traceback (most recent call last):
  File "/opt/edb/livecompare/venv/lib/python3.9/site-packages/livecompare/live_compare.py", line 1382, in recheck
    if v_difference.Initialize():
  File "/opt/edb/livecompare/venv/lib/python3.9/site-packages/livecompare/live_difference.py", line 151, in Initialize
    if self.GetMetaData():
  File "/opt/edb/livecompare/venv/lib/python3.9/site-packages/livecompare/live_difference.py", line 72, in GetMetaData
    if not self.Tables[k].table_exists:
AttributeError: 'LiveTable' object has no attribute 'table_exists'

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/main/product_docs/docs/livecompare/3/command_line_usage.mdx

**Comment by djw-m** [comment]
This issue has been passed to the livecompare team as it is not a documentation issue.
