### ISSUE TITLE
I encounter problem while using Migration Toolkit ver 55

### ISSUE THREAD

**Issue by soheiltf** [EnterpriseDB/docs#6357]
### What topic do you have feedback on?

To migrate my database from Oracle 19 to PostgreSQL 17, I used EDB Migration Toolkit ver 55. I followed everything mentioned in the documentation on the  [(product website)](https://www.enterprisedb.com/docs/migration_toolkit/latest/) but encountered a blocker problem.

### Your feedback

First, I changed the toolkit.properties with proper values for SRC and Target DB as below
SRC_DB_URL=jdbc:oracle:thin:@198.100.101.208:1521:sidname
SRC_DB_USER=.....
SRC_DB_PASSWORD=...

TARGET_DB_URL=jdbc:postgresql://localhost:5432/postgres
TARGET_DB_USER=postgres
TARGET_DB_PASSWORD=....

and then executed the following commands:
.\runMTK.bat -targetdbtype postgresql -verbose on -targetSchema MY_DEST_SCHEMA SELECTED_SCHEMA_IN_ORA

But I received the following error:
2024-12-18 15:20:23 Connecting with target Postgres database server...
2024-12-18 15:20:23 MTK-11009: Error Connecting Database "PostgreSQL"
DB-99999: org.postgresql.util.PSQLException: Something unusual has occurred to cause the driver to fail. Please report this exception.
java.lang.NoSuchFieldError: Class org.postgresql.shaded.com.ongres.scram.common.stringprep.StringPreparations does not have member field 'org.postgresql.shaded.com.ongres.scram.common.stringprep.StringPreparations SASL_PREPARATION'
2024-12-18 15:20:23 Stack Trace:
com.edb.MTKException: MTK-11009: Error Connecting Database "PostgreSQL"
DB-99999: org.postgresql.util.PSQLException: **Something unusual has occurred to cause the driver to fail. Please report this exception.**
java.lang.NoSuchFieldError: Class org.postgresql.shaded.com.ongres.scram.common.stringprep.StringPreparations does not have member field 'org.postgresql.shaded.com.ongres.scram.common.stringprep.StringPreparations SASL_PREPARATION'
	at com.edb.common.MTKFactory.createMTKConnection(MTKFactory.java:244) ~[edb-migrationtoolkit.jar:?]
	at com.edb.MigrationToolkit.createNewTargetConnection(MigrationToolkit.java:7644) ~[edb-migrationtoolkit.jar:?]
	at com.edb.MigrationToolkit.initToolkit(MigrationToolkit.java:3980) ~[edb-migrationtoolkit.jar:?]
	at com.edb.MigrationToolkit.main(MigrationToolkit.java:2095) [edb-migrationtoolkit.jar:?]
Caused by: org.postgresql.util.PSQLException: Something unusual has occurred to cause the driver to fail. Please report this exception.
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:401) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.Driver.connect(Driver.java:305) ~[postgresql-42.7.3.jar:42.7.3]
	at com.edb.dbhandler.postgresql.PGConnection.<init>(PGConnection.java:39) ~[edb-migrationtoolkit.jar:?]
	at com.edb.common.MTKFactory.createMTKConnection(MTKFactory.java:241) ~[edb-migrationtoolkit.jar:?]
	... 3 more
Caused by: java.lang.NoSuchFieldError: Class org.postgresql.shaded.com.ongres.scram.common.stringprep.StringPreparations does not have member field 'org.postgresql.shaded.com.ongres.scram.common.stringprep.StringPreparations SASL_PREPARATION'
	at org.postgresql.jre7.sasl.ScramAuthenticator.processServerMechanismsAndInit(ScramAuthenticator.java:76) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:855) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:207) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.Driver.makeConnection(Driver.java:446) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.Driver.access$100(Driver.java:63) ~[postgresql-42.7.3.jar:42.7.3]
	at org.postgresql.Driver$ConnectThread.run(Driver.java:355) ~[postgresql-42.7.3.jar:42.7.3]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
2024-12-18 15:20:23 
2024-12-18 15:20:23 One or more schema objects could not be imported during the migration process. Please review the migration output for more details.
2024-12-18 15:20:23 Total Elapsed Migration Time (sec): 3.405
2024-12-18 15:20:23 
Migration logs have been saved to ....\.enterprisedb\migration-toolkit\logs
2024-12-18 15:20:23 
******************** Migration Summary ********************

Total objects: 0
Successful count: 0
Failed count: 0
Invalid count: 0

**Comment by gvasquezvargas** [comment]
Hi @soheiltf 
Our engineering team has answered: 

The specific error is related to a missing dependency in the PostgreSQL JDBC driver jar. The customer is using an old JDBC driver. We recommend trying out the latest PostgreSQL JDBC driver (ver 42.7.3 or later).

I hope this helps you troubleshoot further.

**Comment by gvasquezvargas** [comment]
Hi all! We added a support matrix and other docs improvements to make JDBC compatibility clearer: https://www.enterprisedb.com/docs/migration_toolkit/latest/02_supported_operating_systems_and_database_versions/#supported-postgres-jdbc-drivers
